import { Bot, Info } from "lucide-react";
import { cn } from "@/lib/cn";
import type { Recommendation, RecommendationStance } from "@/lib/types";

const STANCE: Record<RecommendationStance, { label: string; cls: string }> = {
  RECOMMEND_QUALIFY: { label: "Appears compliant", cls: "bg-success-bg text-success border-success/30" },
  FURTHER_SCRUTINY: { label: "Needs further scrutiny", cls: "bg-warning-bg text-warning border-warning/30" },
  RECOMMEND_DISQUALIFY: {
    label: "Does not appear to meet mandatory eligibility",
    cls: "bg-danger-bg text-danger border-danger/30",
  },
};

export function RecommendationPanel({ recommendation }: { recommendation: Recommendation }) {
  const s = STANCE[recommendation.stance];
  return (
    <div>
      <div className="mb-3 flex items-center gap-2">
        <span className="flex h-8 w-8 items-center justify-center rounded-lg bg-primary-50 text-primary">
          <Bot aria-hidden className="h-5 w-5" />
        </span>
        <div>
          <p className="text-sm font-semibold text-ink-900">AI recommendation</p>
          <p className="text-2xs font-medium uppercase tracking-wide text-secondary-dark">
            Advisory — the officer decides
          </p>
        </div>
      </div>

      <div className={cn("rounded-input border px-3 py-2 text-sm font-semibold", s.cls)}>
        For the officer&apos;s consideration: {s.label}.
      </div>

      <p className="mt-3 text-sm leading-relaxed text-ink-700">{recommendation.rationale}</p>

      {recommendation.evidence_refs.length > 0 && (
        <div className="mt-3">
          <p className="text-2xs font-semibold uppercase tracking-wide text-ink-500">
            Grounded in evidence
          </p>
          <div className="mt-1.5 flex flex-wrap gap-1.5">
            {recommendation.evidence_refs.map((ref) => (
              <span
                key={ref}
                className="tnum rounded-full border border-border bg-surface-1 px-2 py-0.5 text-2xs text-ink-700"
              >
                {ref}
              </span>
            ))}
          </div>
        </div>
      )}

      <p className="mt-3 flex items-start gap-1.5 rounded-input bg-surface-1 px-3 py-2 text-2xs text-ink-500">
        <Info aria-hidden className="mt-0.5 h-3.5 w-3.5 shrink-0" />
        Generated by {recommendation.model_meta.provider} ({recommendation.model_meta.model}). PRAMAAN
        never auto-disqualifies — this is decision support only.
      </p>
    </div>
  );
}
